### ISSUE TITLE
dont get plugin copytags working.

### ISSUE THREAD

**Issue by cloudstrife11** [niemands/StashPlugins#2]
When press create copytags tag it gives me this [Plugin] Copied scene information to 0 galleries It not create tags to images

**Comment by niemands** [comment]
I admit that the description is rather vague.  The 'Create CopyTags tag' task should only create the corresponding tag, alternatively you can create it manually. Then you have to add the tag to all galleries where you want to copy the information and press the 'Copy tags' button. The output you describe should only appear in this task.
I have updated the plugin and added more debug output. Could you please give me the output of this if it still doesn't work?

**Comment by cloudstrife11** [comment]
this is what I get : 0-10-22 18:36:38
Debug   
Plugin returned: ok
2020-10-22 18:36:38
Info    
[Plugin] Copied scene information to 0 galleries
2020-10-22 18:36:38
Debug   
[Plugin] Found 0 galleries with CopyTags tag
2020-10-22 18:36:38
Debug   
SQL: SELECT DISTINCT galleries.id FROM galleries 
		left join performers_galleries as performers_join on performers_join.gallery_id = galleries.id
		left join studios as studio on studio.id = galleries.studio_id
		left join galleries_tags as tags_join on tags_join.gallery_id = galleries.id
		left join galleries_images as images_join on images_join.gallery_id = galleries.id
		left join images on images_join.image_id = images.id
	 LEFT JOIN tags on tags_join.tag_id = tags.id WHERE tags.id IN (?) GROUP BY galleries.id  HAVING count(distinct tags.id) IS 1 ORDER BY galleries.path ASC LIMIT 100 OFFSET 0 , args: [775]

**Comment by cloudstrife11** [comment]
I think I just dont understand how this works

**Comment by cloudstrife11** [comment]
I just dont understand how it works. Maybe I am just to dumb:(. What I did is just click on the plugin (create copytags tags), but I think I need to do more then this right. because it now gives me : [Plugin] Tag already exists, But If I press on (Copy tags) It gives me this : 
20-10-22 18:58:00
Debug   
Plugin returned: ok
2020-10-22 18:58:00
Info    
[Plugin] Copied scene information to 0 galleries
2020-10-22 18:58:00
Debug   
[Plugin] Found 0 galleries with CopyTags tag
2020-10-22 18:58:00
Debug   
SQL: SELECT DISTINCT galleries.id FROM galleries 
		left join performers_galleries as performers_join on performers_join.gallery_id = galleries.id
		left join studios as studio on studio.id = galleries.studio_id
		left join galleries_tags as tags_join on tags_join.gallery_id = galleries.id
		left join galleries_images as images_join on images_join.gallery_id = galleries.id
		left join images on images_join.image_id = images.id
	 LEFT JOIN tags on tags_join.tag_id = tags.id WHERE tags.id IN (?) GROUP BY galleries.id  HAVING count(distinct tags.id) IS 1 ORDER BY galleries.path ASC LIMIT 100 OFFSET 0 , args: [775]

**Comment by niemands** [comment]
The plugin found no gallery with the CopyTags tag.
You need to add the tag to all galleries where you want to copy the information from the scene and then click on `Copy tags`
Or do you want to have an option to copy the information from all scenes to their attached galleries?

**Comment by cloudstrife11** [comment]
Yes if that is possible to have this option to copy the information from all scenes to their attached galleries?.

**Comment by niemands** [comment]
I have added the task, however I have only tested it with a rudimentary test setup, so it might be worth making a backup beforehand.

**Comment by cloudstrife11** [comment]
Srry for not replying so long. I had problems all the time with stash. but now I getting that fixed. I now run; I getting this command: 20-10-31 19:21:18
Info    
[Plugin] Copied scene information to 35 galleries
2020-10-31 19:21:17
Info    
[Plugin] Start copying information. This may take a while depending on the amount of galleries
2020-10-31 19:20:47
Warning 
[Plugin] #######################################
2020-10-31 19:20:47
Warning 
[Plugin] You have 30 seconds to cancel this task before it starts copying
2020-10-31 19:20:47
Warning 
[Plugin] Warning! This task will copy all information to all galleries with attached scenes
2020-10-31 19:20:47
Warning 
[Plugin] #######################################
