### ISSUE TITLE
The stash_interface.py is not working if Authentication is enabled

### ISSUE THREAD

**Issue by Y0ngg4n** [niemands/StashPlugins#5]
All the Requests should not work if Authentication is enabled at the stash Instance.
[See here](https://github.com/stashapp/stash/wiki/API)

**Comment by niemands** [comment]
The plugin gets a cookie used for authentication from stash, which will be passed to the StashInterface in the constructor like e.g. in the set_ph_urls.py
```python
def main():
    json_input = readJSONInput()

    client = StashInterface(json_input.get('server_connection'))
```

https://github.com/niemands/StashPlugins/blob/86533d6b510ed9d2ee3ff6c13ddb0863e17edcf7/py_plugins/stash_interface.py#L22

**Comment by Y0ngg4n** [comment]
@niemands oh OK sorry my mistake :)
